@startuml

    right header
        <font size=20 color=black>Package: <b>UCP</b></font>
    end header

    actor "Користувач" as User #fff8bd
    actor "Менеджер" as Manager #bbdaff

    note right of Manager #f0f0f0
        Власник наборів даних,
        які створив. Може керувати
        лише власними наборами.
    end note
    
    usecase "<b>UC.u.1</b>\nЗнайти набори даних" as UC.u.1 #d0eeb0
    usecase "<b>UC.u.2</b>\nЗавантажити набір даних" as UC.u.2 #d0eeb0
    usecase "<b>UC.u.3</b>\nСтворити акаунт менеджера" as UC.u.3 #fff8bd

    usecase "<b>UC.m.a</b>\nУвійти в акаунт" as UC.m.a #bbdaff
    usecase "<b>UC.m.1</b>\nПереглянути набір даних" as UC.m.1 #bbdaff
    usecase "<b>UC.m.2</b>\nСтворити набір даних" as UC.m.2 #bbdaff
    usecase "<b>UC.m.m</b>\nКерувати набором даних" as UC.m.m #90c0ff
    usecase "<b>UC.m.m.1</b>\nЗмінити набір даних" as UC.m.m.1 #90c0ff
    usecase "<b>UC.m.m.2</b>\nДодати співавтора набору даних" as UC.m.m.2 #90c0ff
    usecase "<b>UC.m.m.3</b>\nВидалити співавтора набору даних" as UC.m.m.3 #90c0ff
    usecase "<b>UC.m.m.4</b>\nВидалити набір даних" as UC.m.m.4 #90c0ff

    note right of UC.m.m.1 #f0f0f0
        Можуть і співавтори набору.
    end note

    UC.u.2 .d.> UC.u.1 : extends

    UC.m.1 .l.> UC.m.a : extends
    UC.m.2 .u.> UC.m.a : extends
    UC.m.m .l.> UC.m.1 : extends
    UC.m.m.1 -d-|> UC.m.m
    UC.m.m.2 -l-|> UC.m.m
    UC.m.m.3 -u-|> UC.m.m
    UC.m.m.4 -u-|> UC.m.m

    User -l-> UC.u.1
    User -u-> UC.u.3

    Manager -u-> UC.u.1
    Manager -d-> UC.m.a
    
    right footer
        <b>Bricks</b>
        НТУУ "КПІ"
        Київ — 2020
    end footer

@enduml
