@startuml

    |Користувач|

        start;

        #fff8bd:Натискає на кнопку реєстрації;

    |Система|

        #f0f0f0:Надає реєстраційну форму;
        
    |Користувач|

        #fff8bd:Заповнює й надсилає
        реєстраційну форму;

    |Система|

        #f0f0f0:Перевіряє дані з
        реєстраційної форми;

        note right #f77
            Можливі <b><i>EX.u.3.1</i></b>,
            <b><i>EX.u.3.2</i></b>
        end note

        #f0f0f0:Вносить дані про новий
        акаунт в базу даних;

        #f0f0f0:Повідомляє про
        створений акаунт;

        stop;

    right footer
        <b>Bricks</b>
        НТУУ "КПІ"
        Киів — 2020
    end footer

@enduml
