@startuml

    |Менеджер|

        start;

        #bbdaff:Авторизується за <b><i>UC.m.a</i></b>;

        #bbdaff:Натискає на кнопку відображення
        своїх наборів даних;

    |Система|

        #f0f0f0:Отримує інформацію з бази даних
        про набори даних менеджера;

        #f0f0f0:Відображає набори
        даних менеджера;
        
    |Менеджер|

        #bbdaff:Обирає бажаний набір;

    |Система|

        #f0f0f0:Відображає сторінку
        обраного набору;

        stop;

    right footer
        <b>Bricks</b>
        НТУУ "КПІ"
        Київ — 2020
    end footer

@enduml