@startuml

    |Менеджер|

        start;

        #90c0ff:Авторизується за <b><i>UC.m.1</i></b>;

        #90c0ff:Натискає на кнопку відображення
        своїх наборів даних;

    |Система|

        #f0f0f0:Отримує інформацію з бази даних
        про набори даних менеджера;

        #f0f0f0:Відображає набори
        даних менеджера;
        
    |Менеджер|

        #90c0ff:Обирає бажаний набір;

    |Система|

        #f0f0f0:Відображає сторінку
        обраного набору;
        
    |Менеджер|

        #90c0ff:Натискає на кнопку
        відображення співавторів;

    |Система|

        #f0f0f0:Відображає співавторів
        обраного набору;
        
    |Менеджер|

        #90c0ff:Натискає на кнопку видалення
        на бажаному співавторі;

    |Система|

        #f0f0f0:Запитує пароль для
        підтвердження дії;

    |Менеджер|

        #90c0ff:Уводить пароль;

    |Система|

        #f0f0f0:Перевіряє введений
        пароль на правильність;

        note right #f77
            Можлива <b><i>EX.m.m.5.1</i></b>
        end note

        #f0f0f0:Видаляє зі спавівторів обраного набору
        в базі даних вказаного співавтора;

        #f0f0f0:Повідомляє про видаленого співавтора;

        #f0f0f0:Сповіщає двидаленого співавтора про
        позбавлення прав щодо обраного набору;

        stop;

    right footer
        <b>Bricks</b>
        НТУУ "КПІ"
        Київ — 2020
    end footer

@enduml