@startuml

    |Менеджер|

        start;

        #90c0ff:Авторизується за <b><i>UC.m.1</i></b>;

        #90c0ff:Натискає на кнопку відображення
        своїх наборів даних;

    |Система|

        #f0f0f0:Отримує інформацію з бази даних
        про набори даних менеджера;

        #f0f0f0:Відображає набори
        даних менеджера;
        
    |Менеджер|

        #90c0ff:Обирає бажаний набір;

    |Система|

        #f0f0f0:Відображає сторінку
        обраного набору;
        
    |Менеджер|

        #90c0ff:Натискає на кнопку
        додання співавтора;

    |Система|

        #f0f0f0:Запитує пароль для
        підтвердження дії;

    |Менеджер|

        #90c0ff:Уводить пароль;

    |Система|

        #f0f0f0:Перевіряє введений
        пароль на правильність;

        note right #f77
            Можлива <b><i>EX.m.m.4.1</i></b>
        end note

        #f0f0f0:Надає поле для введення імені
        акаунта майбутнього
        менеджера-співавтора;
        
    |Менеджер|

        #90c0ff:Уводить ім'я акаунта майбутнього
        менеджера-співавтора;

    |Система|

        #f0f0f0:Здійснює пошук уведеного
        імені акаунта в базі даних;

        note right #f77
            Можлива <b><i>EX.m.m.4.2</i></b>
        end note

        #f0f0f0:Вносить у базу даних вказаного
        нового співавтора обраного набору;

        #f0f0f0:Повідомляє про доданого співавтора;

        #f0f0f0:Сповіщає доданого співавтора про
        надані права щодо обраного набору;

        stop;

    right footer
        <b>Bricks</b>
        НТУУ "КПІ"
        Киів — 2020
    end footer

@enduml
