@startuml

    right header
        <font size=20 color=black><b>UC.m.m</b></font>
    end header

    actor "Менеджер" as Manager #bbdaff

    usecase "<b>UC.m.m</b>\nКерувати наборами даних" as UC.m.m #86baff

    usecase "<b>UC.m.m.4</b>\nСтворити набір даних" as UC.m.m.4 #bbdaff
    usecase "<b>UC.m.m.5</b>\nЗмінити набір даних" as UC.m.m.5 #bbdaff
    usecase "<b>UC.m.m.6</b>\nДодати співавтора набору даних" as UC.m.m.6 #bbdaff
    usecase "<b>UC.m.m.7</b>\nВидалити співавтора набору даних" as UC.m.m.7 #bbdaff
    usecase "<b>UC.m.m.8</b>\nВидалити набір даних" as UC.m.m.8 #bbdaff

    note left of UC.m.m.5 #d9eaff
        Можуть і співавтори.
    end note

    UC.m.m.4 .r.> UC.m.m : extends
    UC.m.m.5 .u.> UC.m.m : extends
    UC.m.m.6 .u.> UC.m.m : extends
    UC.m.m.7 .u.> UC.m.m : extends
    UC.m.m.8 .l.> UC.m.m : extends

    Manager -d-> UC.m.m
    
    right footer
        <b>Bricks</b>
        НТУУ "КПІ"
        Київ — 2020
    end footer

@enduml