@startuml

entity User #fff8bd {}
entity User.username #fffbdc {}
entity User.id #fffbdc {}
entity User.password #fffbdc {}

entity Manager #aed3ff {}

Manager --|> User

entity Dataset #86baff {}
entity Dataset.id #e0eeff {}
entity Dataset.concepts_id #e0eeff {}
entity Dataset.entities_id #e0eeff {}
entity Dataset.datapoints_id #e0eeff {}
entity Dataset.synonyms_id #e0eeff {}
entity Dataset.metadata_id #e0eeff {}

Manager "0, *"--"1, *" Dataset

entity Concepts #aed3ff {}
entity Concepts.id #e0eeff {}
entity Concepts.concept #e0eeff {}
entity Concepts.type #e0eeff {}
entity Concepts.unit #e0eeff {}

Concepts "0, *"-u-"1, 1" Dataset

entity Entities #aed3ff {}
entity Entities.id #e0eeff{}

Entities "0, *"-u-"1, 1" Dataset

entity Datapoints #aed3ff {}
entity Datapoints.id #e0eeff {}
entity Datapoints.key #e0eeff {}
entity Datapoints.datapoint #e0eeff {}

Datapoints "0, *"-u-"1, 1" Dataset

entity Synonyms #aed3ff {}
entity Synonyms.id #e0eeff {}
entity Synonyms.concept #e0eeff {}
entity Synonyms.synonym #e0eeff {}

Synonyms "0, *"-u-"1, 1" Dataset

entity Metadata #aed3ff {}
entity Metadata.id #e0eeff {}
entity Metadata.key #e0eeff {}
entity Metadata.value #e0eeff {}
entity Metadata.filter #e0eeff {}
entity Metadata.metadata #e0eeff {}

Metadata "0, *"-u-"1, 1" Dataset

User.username -u-* User
User.id -u-* User
User.password -u-* User

Dataset.id -d-* Dataset
Dataset.concepts_id -d-* Dataset
Dataset.entities_id -d-* Dataset
Dataset.datapoints_id -d-* Dataset
Dataset.synonyms_id -d-* Dataset
Dataset.metadata_id -d-* Dataset

Concepts.id -u-* Concepts
Concepts.concept -u-* Concepts
Concepts.type -u-* Concepts
Concepts.unit -u-* Concepts

Entities.id --* Entities

Datapoints.id --* Datapoints
Datapoints.key --* Datapoints
Datapoints.datapoint --* Datapoints

Synonyms.id --* Synonyms
Synonyms.concept --* Synonyms
Synonyms.synonym --* Synonyms

Metadata.id -u-* Metadata
Metadata.key -u-* Metadata
Metadata.value -u-* Metadata
Metadata.filter -u-* Metadata
Metadata.metadata -u-* Metadata

@enduml