@startuml

  entity Набір {
    name:TEXT
    Entities: Entities
    Datapoints: Datapoints
    Metadata: Metadata
    Concepts: Concepts
    Synonyms: Synonyms
  }
  
  entity Менеджер {
    name:TEXT
  }
  
  entity Зміна {
    name:TEXT
  }
  
  entity Entities {
    date: DATE
    quantity: NUMBER
  }

  entity Datapoints {
    date: DATE
    quantity: NUMBER
  }
  
    entity Metadata {
    date: DATE
    quantity: NUMBER
  }
  
    entity Concepts {
    date: DATE
    quantity: NUMBER
  }
  
    entity Synonyms {
    date: DATE
    quantity: NUMBER
  }
  
  Зміна "0,*"-- "1,1" Менеджер
  Менеджер "0,*"-- "1,*" Набір
  Entities "0,*"-- "1,1" Зміна
  Datapoints "0,*"-- "1,1" Зміна
  Metadata "0,*"-- "1,1" Зміна
  Concepts "0,*"-- "1,1" Зміна
  Synonyms "0,*"-- "1,1" Зміна
    
@enduml
