@startuml

entity Dataset #86baff {
    id: INT
}

entity Concepts #aed3ff {
    id: INT
    concept: TEXT
    type: TYPE
    unit: TEXT
}

entity CLink #f0f0f0 {}

Dataset "1, 1"-u-"0, *" CLink
Concepts "1, 1"-d-"0, *" CLink

entity Entities #aed3ff {
    id: INT
    key
    table
}

entity ELink #f0f0f0 {}

Dataset "1, 1"-u-"0, *" ELink
Entities "1, 1"-d-"0, *" ELink

entity Datapoints #aed3ff {
    id: INT
    key
    table
}

entity DLink #f0f0f0 {}

Dataset "1, 1"-u-"0, *" DLink
Datapoints "1, 1"-d-"0, *" DLink

entity Synonyms #aed3ff {
    id: INT
    concept: TEXT
    synonym: TEXT
}

entity SLink #f0f0f0 {}

Dataset "1, 1"-u-"0, *" SLink
Synonyms "1, 1"-d-"0, *" SLink

entity Metadata #aed3ff {
    id: INT
    key
    value
    filter
    metadata: TEXT
}

Metadata "0, *"-d-"1, 1" Datapoints
Metadata "0, *"-d-"1, 1" Entities
Metadata "0, *"-d-"1, 1" Concepts


@enduml