|Користувач| натискає на кнопку завантаження набору данних
|Система| відкриває вікно з вибором формату файлу, в якому буде поданний набір данних. Є 3 формати: csv, json, xml , кожний з них має кнопку для скачування набору данних у цьомцу форматі
|Користувач| Натискає на кнопку з вибранним форматом
|Система| передає набір данних у файлі обранного формату на браузер, а браузер завантажує цей файл на комп'ютер 